### ISSUE TITLE
how can I add reCAPTCHA to form

### ISSUE THREAD

**Issue by alfredogama** [Alekseon/magento2-custom-forms-builder#10]
Hello! 
I wanna add reCAPTCHA to the new form. How to add this? I saw in the example this feature.

warm regards.
Alfredo

**Comment by Linek** [comment]
HI @alfredogama 

Please make sure that you have all required extensions installed:
- https://github.com/Alekseon/magento2-widget-forms
- https://github.com/Alekseon/magento2-widget-forms-re-captcha

**Tip**: The easiest is to install using composer which is described here: https://github.com/Alekseon/magento2-widget-forms

Once you will have it install the extension will use Magento Google Captcha in the fields which you will specify.

Hope this will help.

**Comment by marcinfr** [comment]
You can also find some usefull informations here: https://github.com/Alekseon/magento2-widget-forms/wiki/reCAPTCHA-Validation
