### ISSUE TITLE
Support for PHP  8.1

### ISSUE THREAD

**Issue by gfxguru** [Alekseon/magento2-custom-forms-builder#11]
Do you plan on supporting Magento 2.4?

**Comment by Linek** [comment]
Hi @gfxguru .

What kind of issue do you have on PHP 8.1?
We'll test it for sure within coming days, but we didn't have any signals that extension is not working on M2.4. I'm just not sure if we were testing on 7.x or 8.x

**Comment by marcinfr** [comment]
Hi @gfxguru 

I have tested extension on PHP 8.1 and Magento 2.4.4. I have applied few small fixes. 
Please update extension to latest version.

If You have any issues with extension, please let us know.
