### ISSUE TITLE
Email - how to set "Reply to" as customer email

### ISSUE THREAD

**Issue by FilipS02** [Alekseon/magento2-custom-forms-builder#14]
Hi, I want to achieve that if I click Reply in email, that the reply to email will be autofilled - the email that customer entered in contact form should be there. Can you help me please? Thanks

**Comment by marcinfr** [comment]
Hi @FilipS02 ,

You have to select which attribute contains customer email, there is configuration in form edit -> confirmation email Tab -> **Customer Email Field**

<img src="https://i.imgur.com/n1ebWpN.png"/>

Please, let me know if it works for You.
BR

**Comment by FilipS02** [comment]
Hi, I have selected the email field though the reply to email isn't the customer's email.

**Comment by marcinfr** [comment]
Hi, can You give us more details?
Screenshot of Your configuration, version of module, and headers of this email?

**Comment by FilipS02** [comment]
I tried it one more time and now the reply to email is filled in correctly. Thanks.
