### ISSUE TITLE
After installation backend not work

### ISSUE THREAD

**Issue by rubenb955** [Alekseon/magento2-custom-forms-builder#16]
Hello after install i have this issue on backend main.CRITICAL: Magento\Framework\Exception\LocalizedException: Invalid requested attribute: title at /vendor/alekseon/alekseon-eav/Model/ResourceModel/Entity/Collection.php:90

**Comment by marcinfr** [comment]
Hello @rubenb955 

Unfortunately I am not able to reproduce the issue.

It seems that form attribute "title" is missing.
Have You notice any errors during setup/upgrade ?
What is Your magento version and which version of extension have You installed?

Can You check if this attribute exists in Your database?
`select * from alekseon_custom_form_attribute where attribute_code = 'title';`

It should be created by this patch:
`Alekseon/CustomFormsBuilder/Setup/Patch/Data/CreateWidgetFormsAttributesPatch.php`

Please check if this patch has been installed
`select * from patch_list where patch_name="Alekseon\\CustomFormsEmailNotification\\Setup\\Patch\\Data\\CreateWidgetFormsAttributesPatch";`

**Comment by ajinkya011** [comment]
Hi, 
I am using Magento 2.3 version & this patch is not getting installed & admin panel is not working, please help me on this.

**Comment by marcinfr** [comment]
Hi @ajinkya011 
Do You notice any error during setup:upgrade commnd ?

**Comment by marcinfr** [comment]
Closed due to inactivity, If You still have issue please reopen ticket or create new one with more details.
