### ISSUE TITLE
Error at php bin/magento setup:upgrade

### ISSUE THREAD

**Issue by aljosamotore** [Alekseon/magento2-custom-forms-builder#4]
I get this error when I try to run command bin/magento setup:upgrade

Impossible to process constructor argument Parameter #0 [ <required> Alekseon\AlekseonEav\Setup\EavSchemaSetupFactory $eavSetupFactory ] of Alekseon\CustomFormsBuilder\Setup\InstallSchema class

And then at compile I get:
MiBPHP Fatal error:  Uncaught Error: Class 'Alekseon\AlekseonEav\Model\Entity' not found in /public_html/app/code/Alekseon/CustomFormsBuilder/Model/FormRecord.php:12

**Comment by Linek** [comment]
Hi @aljosamotore 

Did you install the extension by composer? It's important to have alekseon/alekseon-eav extension installed to have it working.

In case you have it missing please use `composer require alekseon/alekseon-eav`

Let me know if that helped.
